apiVersion: v1
kind: Service
metadata:
  name: security-playground-restricted
  namespace: security-playground-restricted
  labels:
    app.kubernetes.io/name: security-playground-restricted
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30001
  selector:
    app.kubernetes.io/name: security-playground-restricted