apiVersion: v1
kind: Service
metadata:
  name: security-playground-restricted-nodrift
  namespace: security-playground-restricted-nodrift
  labels:
    app.kubernetes.io/name: security-playground-restricted-nodrift
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30002
  selector:
    app.kubernetes.io/name: security-playground-restricted-nodrift