kind: Service
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: hello-server
  name: hello-server
  namespace: hello
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: hello-server
  sessionAffinity: None
  type: ClusterIP